### ISSUE TITLE
[Usage] Fine-tune with 4 x 40G A100 gpus and get OOM error when saving state_dict

### ISSUE THREAD

**Issue by o0t1ng0o** [haotian-liu/LLaVA#177]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Hi, @haotian-liu 
Issue: 
I downloaded the liuhaotian/LLaVA-7b-delta-v0 model from huggingface.
I fine-tuned this model with my custom dataset with 4 x 40G A100 gpus.
But I got OOM error when I saved the model.
And my per_device_train_batch_size=1.

Command:
```
python3 -m torch.distributed.run --nnodes=1 --nproc_per_node=4 --master_port=25001 \
    llava/train/train_mem.py \
    --model_name_or_path ./LLaVA-7b-delta-v0 \
    --data_path ./trainset.json \
    --image_folder ./images \
    --vision_tower ./clip-vit-large-patch14 \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True \
    --bf16 True \
    --output_dir ./checkpoints \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 5000 \
    --save_total_limit 3 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --report_to wandb
```

Log: 
```
  warnings.warn(
/my/path/tool/anaconda3/envs/llava_beta/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py:312: UserWarn
ing: Failed to clone() tensor with name lm_head.weight on rank 2. This may mean that this state_dict entry could point to invalid memory regions after r
eturning from state_dict() call if this parameter is managed by FSDP. Please check clone implementation of lm_head.weight. Error: CUDA out of memory. Tr
ied to allocate 502.00 MiB (GPU 2; 39.59 GiB total capacity; 36.99 GiB already allocated; 45.19 MiB free; 37.41 GiB reserved in total by PyTorch) If res
erved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALL$
C_CONF
  warnings.warn(
/my/path/tool/anaconda3/envs/llava_beta/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py:312: UserWar$
ing: Failed to clone() tensor with name _fsdp_wrapped_module.model.layers.31.mlp.up_proj.weight on rank 0. This may mean that this state_dict entry cou$
d point to invalid memory regions after returning from state_dict() call if this parameter is managed by FSDP. Please check clone implementation of _fs$
p_wrapped_module.model.layers.31.mlp.up_proj.weight. Error: CUDA out of memory. Tried to allocate 172.00 MiB (GPU 0; 39.59 GiB total capacity; 37.30 Gi$
 already allocated; 61.19 MiB free; 37.54 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to $
void fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  warnings.warn(
/my/path/tool/anaconda3/envs/llava_beta/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py:312: UserWar$
ing: Failed to clone() tensor with name lm_head.weight on rank 0. This may mean that this state_dict entry could point to invalid memory regions after $
eturning from state_dict() call if this parameter is managed by FSDP. Please check clone implementation of lm_head.weight. Error: CUDA out of memory. T$
ied to allocate 502.00 MiB (GPU 0; 39.59 GiB total capacity; 37.05 GiB already allocated; 61.19 MiB free; 37.54 GiB reserved in total by PyTorch) If re$
erved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALL$
C_CONF
  warnings.warn(
Traceback (most recent call last):
  File "/my/path/wt/code/PLM/LLaVA/llava/train/train_mem.py", line 15, in <module>
    train()
  File "/my/path/wt/code/PLM/LLaVA/llava/train/train.py", line 666, in train
    safe_save_model_for_hf_trainer(trainer=trainer,
  File "/my/path/wt/code/PLM/LLaVA/llava/train/train.py", line 95, in safe_save_model_for_hf_trainer
    cpu_state_dict = {
  File "/my/path/wt/code/PLM/LLaVA/llava/train/train.py", line 96, in <dictcomp>
    key: value.cpu()
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by o0t1ng0o** [comment]
I have solved this issue with this solution. https://discuss.pytorch.org/t/fsdp-failed-to-save-model-checkpoints/178232/2

**Comment by kahnchana** [comment]
Did you figure out any way to solve this without modifying the torch library source code?
