### ISSUE TITLE
NETWORK ERROR DUE TO HIGH TRAFFIC

### ISSUE THREAD

**Issue by gnimyang** [haotian-liu/LLaVA#364]
### Describe the issue

Whenever I create a new folder re-run the program.
if I put the picture into the model, the model will crash busy!
![image](https://github.com/haotian-liu/LLaVA/assets/130719420/e7f8487d-f181-4c9d-8826-353af989ff7d)
if only input text, it can work well.
it seems the model disconnect to the webserver

2023-08-10 16:47:15 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=4, locked=False). global_counter: 1
2023-08-10 16:47:15 | INFO | stdout | INFO:     127.0.0.1:57164 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2023-08-10 16:47:21 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=5, locked=False). global_counter: 1
2023-08-10 16:47:24 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=5, locked=False). global_counter: 1
2023-08-10 16:47:34 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=4, locked=False). global_counter: 2
2023-08-10 16:47:34 | INFO | stdout | INFO:     127.0.0.1:57180 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2023-08-10 16:47:35 | ERROR | stderr | Exception in thread Thread-4 (generate):
2023-08-10 16:47:35 | ERROR | stderr | Traceback (most recent call last):
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2023-08-10 16:47:35 | ERROR | stderr |     self.run()
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/threading.py", line 953, in run
2023-08-10 16:47:35 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2023-08-10 16:47:35 | ERROR | stderr |     return func(*args, **kwargs)
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
2023-08-10 16:47:35 | ERROR | stderr |     return self.sample(
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
2023-08-10 16:47:35 | ERROR | stderr |     outputs = self(
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-08-10 16:47:35 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
2023-08-10 16:47:35 | ERROR | stderr |     output = old_forward(*args, **kwargs)
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/Pycharm_Project/LLaVA/llava/model/language_model/llava_llama.py", line 78, in forward
2023-08-10 16:47:35 | ERROR | stderr |     outputs = self.model(
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-08-10 16:47:35 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 693, in forward
2023-08-10 16:47:35 | ERROR | stderr |     layer_outputs = decoder_layer(
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-08-10 16:47:35 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
2023-08-10 16:47:35 | ERROR | stderr |     output = old_forward(*args, **kwargs)
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 405, in forward
2023-08-10 16:47:35 | ERROR | stderr |     hidden_states = self.input_layernorm(hidden_states)
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-08-10 16:47:35 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
2023-08-10 16:47:35 | ERROR | stderr |     output = old_forward(*args, **kwargs)
2023-08-10 16:47:35 | ERROR | stderr |   File "/public/home/v-yumy/anaconda3/envs/llava2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 89, in forward
2023-08-10 16:47:35 | ERROR | stderr |     return self.weight * hidden_states.to(input_dtype)
2023-08-10 16:47:35 | ERROR | stderr | RuntimeError: CUDA error: device-side assert triggered
2023-08-10 16:47:35 | ERROR | stderr | CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
2023-08-10 16:47:35 | ERROR | stderr | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
2023-08-10 16:47:35 | ERROR | stderr | Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
2023-08-10 16:47:35 | ERROR | stderr |
2023-08-10 16:47:39 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=4, locked=False). global_counter: 2
2023-08-10 16:47:49 | INFO | stdout | Caught Unknown Error
2023-08-10 16:47:49 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=5, locked=False). global_counter: 2
2023-08-10 16:47:54 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=5, locked=False). global_counter: 2
2023-08-10 16:48:09 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=5, locked=False). global_counter: 2
2023-08-10 16:48:24 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=5, locked=False). global_counter: 2
2023-08-10 16:48:39 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=5, locked=False). global_counter: 2
2023-08-10 16:48:54 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=5, locked=False). global_counter: 2
2023-08-10 16:49:09 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=5, locked=False). global_counter: 2
2023-08-10 16:49:24 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=5, locked=False). global_counter: 2
2023-08-10 16:49:39 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=5, locked=False). global_counter: 2
2023-08-10 16:49:55 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=5, locked=False). global_counter: 2
2023-08-10 16:50:10 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=5, locked=False). global_counter: 2
2023-08-10 16:50:25 | INFO | model_worker | Send heart beat. Models: ['01']. Semaphore: Semaphore(value=5, locked=False). global_counter: 2

**Comment by gnimyang** [comment]
Hi Haotian, I have solved this issue, The problem relies on the checkpoint subfolder name. when I randomly name different models like 01, 02, the program will meet above issue. Though, I don't know the reason, but make sure the model-path name should not numbers, or it will not recognize image.

**Comment by haotian-liu** [comment]
Yep, it uses llava to recognize the model to be multimodal. Working to improve this to more intelligently detect the model type. Closing for now.

**Comment by 459737087** [comment]
Thank you! you did a great job @gnimyang
