### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED[Usage] 

### ISSUE THREAD

**Issue by mibri77** [haotian-liu/LLaVA#458]
### Describe the issue

Getting above error  right after i fill the user prompt

**Comment by xiujiesong** [comment]
Hi, I have the same error, do you know how to fix it now?

**Comment by maximotus** [comment]
Same here

**Comment by Arancia111** [comment]
+1 same

**Comment by wanghao9610** [comment]
I have met the issue, the reason is the cuda package mismatches with the PyTorch cuda version.  I have resolved the problem by rechecking the "nvcc -V" and "torch.version.cuda" to ensure the same.
