### ISSUE TITLE
OOM error and fsdp support

### ISSUE THREAD

**Issue by Unrealluver** [haotian-liu/LLaVA#52]
Thanks for your excellent work! I have tried vicuna-13b on 8xA100(40G), but it will result in an OOM error. To avoid the GPU OOM error, I add the following commands to the pretraining scripts:
```
--fsdp "full_shard auto_wrap offload" \  
--fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \  
--bf16 True \
```
 
I got the error: 

```
ValueError: `FlatParameter` requires uniform `requires_grad`
```

Could you please provide some suggestions?

**Comment by haotian-liu** [comment]
Hi, thank you for your interest in our work.  I am also working for this to be supported with a wider range of hardware so that more researchers can benefit from our work.

Currently PyTorch native support for FSDP on parameter efficient tuning (part of the parameters are frozen) is still under-development.  I am trying two potential solutions: (1) use the PyTorch nightly with some minor modification to the `transformers`; (2) use deepspeed for pretraining.

I am currently looking into this, and the first direction seems possible.  I will send an update here tonight.

**Comment by haotian-liu** [comment]
Hey good news, I have made the FSDP with pretraining work, please follow the instructions [here](https://github.com/haotian-liu/LLaVA#experimental-use-fsdp-to-save-memory-in-pretraining).

I verified that with the first 200 iterations (25600 samples), the loss curve is almost identical to that I trained without FSDP on 7B model.  Unfortunately, I may not have the free machine to finish the training to make the full validation today.  You may try this out, as it seems no problem to me.

To be safe, maybe still switch to our stable branch for finetuning which has the native/stable FSDP support from PyTorch.

**Comment by ZhengMengbin** [comment]
> Hey good news, I have made the FSDP with pretraining work, please follow the instructions [here](https://github.com/haotian-liu/LLaVA#experimental-use-fsdp-to-save-memory-in-pretraining).
> 
> I verified that with the first 200 iterations (25600 samples), the loss curve is almost identical to that I trained without FSDP on 7B model. Unfortunately, I may not have the free machine to finish the training to make the full validation today. You may try this out, as it seems no problem to me. It'd be great if you could help try this, and share the results :)
> 
> To be safe, maybe still switch to our stable branch for finetuning which has the native/stable FSDP support from PyTorch.

I follow the instructions, but get [ValueError: Must flatten tensors with uniform `requires_grad` when `use_orig_params=False`] error

GPU: 8 * A100, CUDA117
Pytorch: torch==2.1.0.dev20230424+cu117
Python: 3.9

**Comment by scenarios** [comment]
IMO set the learning rate of all LLaMA-13B parameters to be zero and then make all require_grad=True could be a more reliable solution at this point.

**Comment by Unrealluver** [comment]
When I use the scripts like below:
```
torchrun --nnodes=1 --nproc_per_node=1 --master_port=25301 \
    llava/train/train_mem.py \
    --model_name_or_path /home/zhulianghui/ProjectC_ChatGPT/alpaca-quan/output/vicuna-13b-composite-3gpt-data \
    --data_path /home/zhulianghui/ProjectC_ChatGPT/llava/reference/LLaVA-CC3M-Pretrain-595K/chat_new.json \
    --image_folder /share/project/lianghuizhu/cc3m-llava \
    --vision_tower /home/zhulianghui/ProjectC_ChatGPT/llava/reference/clip-vit-large-patch14 \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True\
    --bf16 True \
    --output_dir ./checkpoints/llava-13b-pretrain_fsdp \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2400 \
    --save_total_limit 1 \
    --learning_rate 2e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --bf16 True \
    --fsdp "full_shard auto_wrap offload" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --run_name "vicuna-13b-clip-l-pretrain" \
    --lazy_preprocess True \
    --report_to mlflow
```

I got the error message like this:
```
Traceback (most recent call last):
  File "/home/zhulianghui/ProjectC_ChatGPT/llava/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/home/zhulianghui/ProjectC_ChatGPT/llava/llava/train/train.py", line 499, in train
    trainer.train()
  File "/home/zhulianghui/.conda/envs/llava_beta/lib/python3.10/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/home/zhulianghui/.conda/envs/llava_beta/lib/python3.10/site-packages/transformers/trainer.py", line 1912, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/zhulianghui/.conda/envs/llava_beta/lib/python3.10/site-packages/transformers/trainer.py", line 2658, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/zhulianghui/.conda/envs/llava_beta/lib/python3.10/site-packages/transformers/trainer.py", line 2690, in compute_loss
    outputs = model(**inputs)
  File "/home/zhulianghui/.conda/envs/llava_beta/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhulianghui/.conda/envs/llava_beta/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 789, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/home/zhulianghui/.conda/envs/llava_beta/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhulianghui/.conda/envs/llava_beta/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 846, in forward
    outputs = self.model(
  File "/home/zhulianghui/.conda/envs/llava_beta/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhulianghui/.conda/envs/llava_beta/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 632, in forward
    raise ValueError("Seems that the image is cut.")
ValueError: Seems that the image is cut.

```
My libs' versions are shown below:
```
torch                    2.1.0.dev20230426+cu118
torchaudio               2.1.0.dev20230426+cu118
torchvision              0.16.0.dev20230426+cu118
```

I will appreciate it if you could share some suggestions!

**Comment by haotian-liu** [comment]
Hi @Unrealluver Are you still facing this issue?

**Comment by haotian-liu** [comment]
@scenarios Thank you for your suggestion.  I have also tried this, but it does not work out very well on my side.  The parameters are all wrapped with the FSDP, so you still need to do `use_orig_params` hack, and the memory cost and training speed also double.  Do you have any suggestions regarding this?  Thanks.

**Comment by Unrealluver** [comment]
> Hi @Unrealluver Are you still facing this issue?

Thanks, I have found the reason.

**Comment by ycchen-tw** [comment]
@Unrealluver Hello, I'm facing the same issue.
`ValueError: `FlatParameter` requires uniform `requires_grad` `
I noticed that you mentioned that you have already resolved it. Could you please share how you resolved it? Thank you!

**Comment by aprilehannibal** [comment]
> > Hi @Unrealluver Are you still facing this issue?
> 
> Thanks, I have found the reason.
 I'm facing the same issue. Could you please share how you resolved it? Thank you!

**Comment by Kobemaomingyuan** [comment]
> Hey good news, I have made the FSDP with pretraining work, please follow the instructions [here](https://github.com/haotian-liu/LLaVA#experimental-use-fsdp-to-save-memory-in-pretraining).
> 
> I verified that with the first 200 iterations (25600 samples), the loss curve is almost identical to that I trained without FSDP on 7B model. Unfortunately, I may not have the free machine to finish the training to make the full validation today. You may try this out, as it seems no problem to me. It'd be great if you could help try this, and share the results :)
> 
> To be safe, maybe still switch to our stable branch for finetuning which has the native/stable FSDP support from PyTorch.

thanks for the information, i use fsdp in LLava but find it occupies a larger amount of GPU memory than deepspeed. have you met the same problem? Here's my setup:
"fsdp": "full_shard auto_wrap",
  "fsdp_transformer_layer_cls_to_wrap": "LlamaDecoderLayer",
  "fsdp_cpu_ram_efficient_loading": true,
  "fsdp_use_orig_params": true,
flash-attn==2.5.8, transformers==4.37.2
