### ISSUE TITLE
[Usage] RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

### ISSUE THREAD

**Issue by unmo** [haotian-liu/LLaVA#769]
### Describe the issue

Issue:
I execute cli command with my custom model. But I get a cuda error when I run it.

Command:
```
python -m llava.serve.cli \
    --model-base "liuhaotian/llava-v1.5-13b"\
    --model-path "./checkpoints/llava1.5_13b_task_lora_epoch1"\
    --image-file ./playground/data/LLaVA-Pretrain/images/test2/4.png
```

Log: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/LLaVA/llava/serve/cli.py", line 124, in <module>
    main(args)
  File "/app/LLaVA/llava/serve/cli.py", line 94, in main
    output_ids = model.generate(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/app/LLaVA/llava/model/language_model/llava_llama.py", line 79, in forward
    ) = self.prepare_inputs_labels_for_multimodal(
  File "/app/LLaVA/llava/model/llava_arch.py", line 183, in prepare_inputs_labels_for_multimodal
    cur_new_input_embeds = torch.cat(cur_new_input_embeds)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)
```

**Comment by DavidK0** [comment]
I had the same issue, adding the --device argument fixed it.

Eg.
python -m llava.serve.cli \
    --model-base "liuhaotian/llava-v1.5-13b"\
    --model-path "./checkpoints/llava1.5_13b_task_lora_epoch1"\
    --image-file ./playground/data/LLaVA-Pretrain/images/test2/4.png\
    --device cuda:0

**Comment by benjiaa** [comment]
@DavidK0 Is this solution compatible with using multiple GPUs? It seems like that's just selecting one GPU. I think that the original poster might have been encountering this problem while intentionally trying to use both of their GPU's (cuda:0 and cuda:1) I encountered this error while trying to use multiple cuda devices because a single card did not have enough video ram.

@unmo  for what it's worth I got around this by using the --load-4bit option to reduce memory footprint and then specify to use only one of my GPU's by prepending CUDA_VISIBLE_DEVICES=0. I'm using the demo interface not cli, but my command is this:

CUDA_VISIBLE_DEVICES=0 python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path ./llava-v1.5-7b --load-4bit

**Comment by uyo9ko** [comment]
Why can't the new version '1.1.3' infer cli.py with multiple GPUs? I switched back to version '1.1.1', and it worked perfectly with no errors like 'Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!'. However, when I use version '1.1.3', it raises this error.

**Comment by unmo** [comment]
I found that new version is not work. So I used new main branch code, but don't know tag version.
Previous version code is good worked.

**Comment by uyo9ko** [comment]
> I found that new version is not work. So I used new main branch code, but don't know tag version. Previous version code is good worked.

Yes. Can you help with this? @haotian-liu

**Comment by haotian-liu** [comment]
Sorry for the inconvenience. It should now be fixed in https://github.com/haotian-liu/LLaVA/commit/4a77fb46181b9354261648613b0b8b7eb35b815c

**Comment by uyo9ko** [comment]
> Sorry for the inconvenience. It should now be fixed in [4a77fb4](https://github.com/haotian-liu/LLaVA/commit/4a77fb46181b9354261648613b0b8b7eb35b815c)

It's solved! Thank you!

**Comment by unmo** [comment]
I resolved it. Thank you.
