### ISSUE TITLE
[Usage] Errors when using Zero3

### ISSUE THREAD

**Issue by ahmedhshahin** [haotian-liu/LLaVA#969]
### Describe the issue

Command:
```
deepspeed llava/train/train_mem.py \
    --deepspeed ./scripts/zero3.json \
    ...
```

Log: 
I am trying to finetune the models using lora and zero 3 on 4 GPUs. However, when I start the experiment on multiple GPUs, training freezes from the beginning. When I try with a single GPU, it raises an error after the first iteration, check below:
```
  0%|                                                                                                                                                                             | 0/32300 [00:00<?, ?it/s]/home/ashahin/.local/lib/python3.9/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
Invalidate trace cache @ step 414: expected module 2612, but got module 2248
{'loss': 3.623, 'learning_rate': 1.0319917440660473e-06, 'epoch': 0.0}                                                                                                                                      
  0%|                                                                                                                                                                 | 1/32300 [00:17<153:24:26, 17.10s/it]Invalidate trace cache @ step 414: expected module 2612, but got module 2248
Invalidate trace cache @ step 414: expected module 2248, but got module 2612
Traceback (most recent call last):
  File "/home/ashahin/codes/bakllava/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/home/ashahin/codes/bakllava/llava/train/train.py", line 1094, in train
    trainer.train()
  File "/home/ashahin/.local/lib/python3.9/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/home/ashahin/.local/lib/python3.9/site-packages/transformers/trainer.py", line 1892, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/ashahin/.local/lib/python3.9/site-packages/transformers/trainer.py", line 2787, in training_step
    self.accelerator.backward(loss)
  File "/home/ashahin/.local/lib/python3.9/site-packages/accelerate/accelerator.py", line 1847, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/home/ashahin/.local/lib/python3.9/site-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/home/ashahin/.local/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/ashahin/.local/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1955, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/home/ashahin/.local/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/ashahin/.local/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 2137, in backward
    self._get_param_coordinator(training=True).reset_step()
  File "/home/ashahin/.local/lib/python3.9/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 203, in reset_step
    raise RuntimeError(f"still have inflight params "
RuntimeError: still have inflight params [{'id': 743, 'status': 'AVAILABLE', 'numel': 2097152, 'ds_numel': 2097152, 'shape': (1024, 1, 8, 16, 16), 'ds_shape': (1024, 1, 8, 16, 16), 'requires_grad': False, 'grad_shape': None, 'persist': False, 'active_sub_modules': set(), 'ds_tensor.shape': torch.Size([2097152])}, {'id': 749, 'status': 'AVAILABLE', 'numel': 1048576, 'ds_numel': 1048576, 'shape': (1024, 1024), 'ds_shape': (1024, 1024), 'requires_grad': False, 'grad_shape': None, 'persist': False, 'active_sub_modules': set(), 'ds_tensor.shape': torch.Size([1048576])}, {'id': 753, 'status': 'AVAILABLE', 'numel': 1048576, 'ds_numel': 1048576, 'shape': (1024, 1024), 'ds_shape': (1024, 1024), 'requires_grad': False, 'grad_shape': None, 'persist': False, 'active_sub_modules': set(), 'ds_tensor.shape': torch.Size([1048576])}, {'id': 757, 'status': 'AVAILABLE', 'numel': 4194304, 'ds_numel': 4194304, 'shape': (4096, 1024), 'ds_shape': (4096, 1024), 'requires_grad': False, 'grad_shape': None, 'persist': False, 'active_sub_modules': set(), 'ds_tensor.shape': torch.Size([4194304])}, {'id': 747, 'status': 'AVAILABLE', 'numel': 1048576, 'ds_numel': 1048576, 'shape': (1024, 1024), 'ds_shape': (1024, 1024), 'requires_grad': False, 'grad_shape': None, 'persist': False, 'active_sub_modules': set(), 'ds_tensor.shape': torch.Size([1048576])}, {'id': 751, 'status': 'AVAILABLE', 'numel': 1048576, 'ds_numel': 1048576, 'shape': (1024, 1024), 'ds_shape': (1024, 1024), 'requires_grad': False, 'grad_shape': None, 'persist': False, 'active_sub_modules': set(), 'ds_tensor.shape': torch.Size([1048576])}]
```

Any idea how to solve this?

**Comment by ahmedhshahin** [comment]
Closing the issue as the problem has been solved by updating other packages in my environment and it's not related to llava.

**Comment by zhyhome** [comment]
> Closing the issue as the problem has been solved by updating other packages in my environment and it's not related to llava.

**How did you solve it?**

**Comment by BlueBlueFF** [comment]
> Closing the issue as the problem has been solved by updating other packages in my environment and it's not related to llava.


Same question How do you fix it?

**Comment by BlueBlueFF** [comment]
> > Closing the issue as the problem has been solved by updating other packages in my environment and it's not related to llava.
> 
> **How did you solve it?**


Same question How do you fix it?

**Comment by ahmedhshahin** [comment]
In my code, I had a for loop that I suspected was the issue when using zero 3. Number of iterations in the loop varied depending on each training sample, so some processes finishes while the others are waiting. Fixing the for loop to have the same number of iterations across all samples solved it. Not sure if this makes sense but it was enough to get my code to run.
